apiVersion: v1
kind: Pod
metadata:
  name: ci-demo-alpine
  namespace: ci-demo
spec:
  serviceAccountName: jenkins
  containers:
  - name: alpine
    image: alpine:3.16
    command:
    - "sleep"
    - "900"
